name: Build and Release Dropzone Navigator

on:
  push:
    tags:
      - 'v*'  # triggers only on version tags like v1.0.0

jobs:
  build:
    name: Build Electron App
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build app
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          case "${{ matrix.os }}" in
            ubuntu-*) npm run build:linux ;;
            windows-*) npm run build:win ;;
            macos-*) npm run build:mac ;;
          esac

      - name: Upload release artifacts
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/*.dmg
            dist/*.exe
            dist/*.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}






